apiVersion: user.pagerduty.m.crossplane.io/v1alpha1
kind: ContactMethod
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/contactmethod
  labels:
    testing.upbound.io/example-name: email
  name: email
  namespace: crossplane-system
spec:
  forProvider:
    address: foo@bar.com
    label: Work
    type: email_contact_method
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: user.pagerduty.m.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: user/v1alpha1/contactmethod
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    email: 125.greenholt.earline@graham.name
    name: Earline Greenholt
