apiVersion: team.pagerduty.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: team/v1alpha1/team
  labels:
    testing.upbound.io/example-name: parent
  name: parent
  namespace: upbound-system
spec:
  forProvider:
    description: Product and Engineering
    name: Product Development
