apiVersion: pagerduty.m.crossplane.io/v1alpha1
kind: StoreConfig
metadata:
  name: vault
  namespace: crossplane-system
spec:
  type: Vault
  defaultScope: crossplane-system
  vault:
    server: http://vault.vault-system:8200
    mountPath: kv2/
    version: v2
    auth:
      method: Token
      token:
        source: Secret
        secretRef:
          name: vault-token
          key: token