/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ActionsAutomationActionHeaderInitParameters struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ActionsAutomationActionHeaderObservation struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ActionsAutomationActionHeaderParameters struct {

	// Name to identify the header
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ActionsAutomationActionParameterInitParameters struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ActionsAutomationActionParameterObservation struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ActionsAutomationActionParameterParameters struct {

	// Name to identify the header
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ActionsPagerdutyAutomationActionInitParameters struct {

	// Id of the Process Automation action to be triggered.
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`
}

type ActionsPagerdutyAutomationActionObservation struct {

	// Id of the Process Automation action to be triggered.
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`
}

type ActionsPagerdutyAutomationActionParameters struct {

	// Id of the Process Automation action to be triggered.
	// +kubebuilder:validation:Optional
	ActionID *string `json:"actionId" tf:"action_id,omitempty"`
}

type CatchAllActionsAutomationActionInitParameters struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	Header []ActionsAutomationActionHeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	Parameter []ActionsAutomationActionParameterInitParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type CatchAllActionsAutomationActionObservation struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	Header []ActionsAutomationActionHeaderObservation `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	Parameter []ActionsAutomationActionParameterObservation `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type CatchAllActionsAutomationActionParameters struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	// +kubebuilder:validation:Optional
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	// +kubebuilder:validation:Optional
	Header []ActionsAutomationActionHeaderParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	// +kubebuilder:validation:Optional
	Parameter []ActionsAutomationActionParameterParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type CatchAllActionsExtractionInitParameters struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type CatchAllActionsExtractionObservation struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type CatchAllActionsExtractionParameters struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	// +kubebuilder:validation:Optional
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	// +kubebuilder:validation:Optional
	Target *string `json:"target" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	// +kubebuilder:validation:Optional
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type CatchAllActionsIncidentCustomFieldUpdateInitParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatchAllActionsIncidentCustomFieldUpdateObservation struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatchAllActionsIncidentCustomFieldUpdateParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type CatchAllActionsVariableInitParameters struct {

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Only regex is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatchAllActionsVariableObservation struct {

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Only regex is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatchAllActionsVariableParameters struct {

	// Name of this Webhook.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`

	// Only regex is supported
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type OrchestrationServiceCatchAllActionsInitParameters struct {

	// Add this text as a note on the resulting incident.
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	AutomationAction []CatchAllActionsAutomationActionInitParameters `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	Extraction []CatchAllActionsExtractionInitParameters `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	IncidentCustomFieldUpdate []CatchAllActionsIncidentCustomFieldUpdateInitParameters `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	PagerdutyAutomationAction []PagerdutyAutomationActionInitParameters `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	Variable []CatchAllActionsVariableInitParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceCatchAllActionsObservation struct {

	// Add this text as a note on the resulting incident.
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	AutomationAction []CatchAllActionsAutomationActionObservation `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	Extraction []CatchAllActionsExtractionObservation `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	IncidentCustomFieldUpdate []CatchAllActionsIncidentCustomFieldUpdateObservation `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	PagerdutyAutomationAction []PagerdutyAutomationActionObservation `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	Variable []CatchAllActionsVariableObservation `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceCatchAllActionsParameters struct {

	// Add this text as a note on the resulting incident.
	// +kubebuilder:validation:Optional
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	// +kubebuilder:validation:Optional
	AutomationAction []CatchAllActionsAutomationActionParameters `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	// +kubebuilder:validation:Optional
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	// +kubebuilder:validation:Optional
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	// +kubebuilder:validation:Optional
	Extraction []CatchAllActionsExtractionParameters `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	// +kubebuilder:validation:Optional
	IncidentCustomFieldUpdate []CatchAllActionsIncidentCustomFieldUpdateParameters `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	// +kubebuilder:validation:Optional
	PagerdutyAutomationAction []PagerdutyAutomationActionParameters `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	// +kubebuilder:validation:Optional
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	// +kubebuilder:validation:Optional
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	// +kubebuilder:validation:Optional
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	// +kubebuilder:validation:Optional
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	// +kubebuilder:validation:Optional
	Variable []CatchAllActionsVariableParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceCatchAllInitParameters struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	Actions []OrchestrationServiceCatchAllActionsInitParameters `json:"actions,omitempty" tf:"actions,omitempty"`
}

type OrchestrationServiceCatchAllObservation struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	Actions []OrchestrationServiceCatchAllActionsObservation `json:"actions,omitempty" tf:"actions,omitempty"`
}

type OrchestrationServiceCatchAllParameters struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	// +kubebuilder:validation:Optional
	Actions []OrchestrationServiceCatchAllActionsParameters `json:"actions" tf:"actions,omitempty"`
}

type OrchestrationServiceInitParameters struct {

	// the catch_all actions will be applied if an Event reaches the end of any set without matching any rules in that set.
	CatchAll []OrchestrationServiceCatchAllInitParameters `json:"catchAll,omitempty" tf:"catch_all,omitempty"`

	// Opt-in/out for switching the Service to Service Orchestrations.
	EnableEventOrchestrationForService *bool `json:"enableEventOrchestrationForService,omitempty" tf:"enable_event_orchestration_for_service,omitempty"`

	// ID of the Service to which this Service Orchestration belongs to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-pagerduty/apis/service/v1alpha1.Service
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a Service in service to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.Reference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a Service in service to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.Selector `json:"serviceSelector,omitempty" tf:"-"`

	// A Service Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
	Set []OrchestrationServiceSetInitParameters `json:"set,omitempty" tf:"set,omitempty"`
}

type OrchestrationServiceObservation struct {

	// the catch_all actions will be applied if an Event reaches the end of any set without matching any rules in that set.
	CatchAll []OrchestrationServiceCatchAllObservation `json:"catchAll,omitempty" tf:"catch_all,omitempty"`

	// Opt-in/out for switching the Service to Service Orchestrations.
	EnableEventOrchestrationForService *bool `json:"enableEventOrchestrationForService,omitempty" tf:"enable_event_orchestration_for_service,omitempty"`

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// ID of the Service to which this Service Orchestration belongs to.
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// A Service Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
	Set []OrchestrationServiceSetObservation `json:"set,omitempty" tf:"set,omitempty"`
}

type OrchestrationServiceParameters struct {

	// the catch_all actions will be applied if an Event reaches the end of any set without matching any rules in that set.
	// +kubebuilder:validation:Optional
	CatchAll []OrchestrationServiceCatchAllParameters `json:"catchAll,omitempty" tf:"catch_all,omitempty"`

	// Opt-in/out for switching the Service to Service Orchestrations.
	// +kubebuilder:validation:Optional
	EnableEventOrchestrationForService *bool `json:"enableEventOrchestrationForService,omitempty" tf:"enable_event_orchestration_for_service,omitempty"`

	// ID of the Service to which this Service Orchestration belongs to.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-pagerduty/apis/service/v1alpha1.Service
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// Reference to a Service in service to populate service.
	// +kubebuilder:validation:Optional
	ServiceRef *v1.Reference `json:"serviceRef,omitempty" tf:"-"`

	// Selector for a Service in service to populate service.
	// +kubebuilder:validation:Optional
	ServiceSelector *v1.Selector `json:"serviceSelector,omitempty" tf:"-"`

	// A Service Orchestration must contain at least a "start" set, but can contain any number of additional sets that are routed to by other rules to form a directional graph.
	// +kubebuilder:validation:Optional
	Set []OrchestrationServiceSetParameters `json:"set,omitempty" tf:"set,omitempty"`
}

type OrchestrationServiceSetInitParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The service orchestration evaluates Events against these Rules, one at a time, and applies all the actions for first rule it finds where the event matches the rule's conditions.
	Rule []OrchestrationServiceSetRuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type OrchestrationServiceSetObservation struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The service orchestration evaluates Events against these Rules, one at a time, and applies all the actions for first rule it finds where the event matches the rule's conditions.
	Rule []OrchestrationServiceSetRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`
}

type OrchestrationServiceSetParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The service orchestration evaluates Events against these Rules, one at a time, and applies all the actions for first rule it finds where the event matches the rule's conditions.
	// +kubebuilder:validation:Optional
	Rule []OrchestrationServiceSetRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type OrchestrationServiceSetRuleActionsInitParameters struct {

	// Add this text as a note on the resulting incident.
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	AutomationAction []RuleActionsAutomationActionInitParameters `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	Extraction []RuleActionsExtractionInitParameters `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	IncidentCustomFieldUpdate []RuleActionsIncidentCustomFieldUpdateInitParameters `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	PagerdutyAutomationAction []ActionsPagerdutyAutomationActionInitParameters `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	Variable []RuleActionsVariableInitParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceSetRuleActionsObservation struct {

	// Add this text as a note on the resulting incident.
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	AutomationAction []RuleActionsAutomationActionObservation `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	Extraction []RuleActionsExtractionObservation `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	IncidentCustomFieldUpdate []RuleActionsIncidentCustomFieldUpdateObservation `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	PagerdutyAutomationAction []ActionsPagerdutyAutomationActionObservation `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	Variable []RuleActionsVariableObservation `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceSetRuleActionsParameters struct {

	// Add this text as a note on the resulting incident.
	// +kubebuilder:validation:Optional
	Annotate *string `json:"annotate,omitempty" tf:"annotate,omitempty"`

	// Create a Webhook associated with the resulting incident.
	// +kubebuilder:validation:Optional
	AutomationAction []RuleActionsAutomationActionParameters `json:"automationAction,omitempty" tf:"automation_action,omitempty"`

	// The ID of the Escalation Policy you want to assign incidents to. Event rules with this action will override the Escalation Policy already set on a Service's settings, with what is configured by this action.
	// +kubebuilder:validation:Optional
	EscalationPolicy *string `json:"escalationPolicy,omitempty" tf:"escalation_policy,omitempty"`

	// sets whether the resulting alert status is trigger or resolve. Allowed values are: trigger, resolve
	// +kubebuilder:validation:Optional
	EventAction *string `json:"eventAction,omitempty" tf:"event_action,omitempty"`

	// Replace any CEF field or Custom Details object field using custom variables.
	// +kubebuilder:validation:Optional
	Extraction []RuleActionsExtractionParameters `json:"extraction,omitempty" tf:"extraction,omitempty"`

	// Assign a custom field to the resulting incident.
	// +kubebuilder:validation:Optional
	IncidentCustomFieldUpdate []RuleActionsIncidentCustomFieldUpdateParameters `json:"incidentCustomFieldUpdate,omitempty" tf:"incident_custom_field_update,omitempty"`

	// Configure a Process Automation associated with the resulting incident.
	// +kubebuilder:validation:Optional
	PagerdutyAutomationAction []ActionsPagerdutyAutomationActionParameters `json:"pagerdutyAutomationAction,omitempty" tf:"pagerduty_automation_action,omitempty"`

	// The ID of the priority you want to set on resulting incident. Consider using the pagerduty_priority data source.
	// +kubebuilder:validation:Optional
	Priority *string `json:"priority,omitempty" tf:"priority,omitempty"`

	// The ID of a Set from this Service Orchestration whose rules you also want to use with events that match this rule.
	// +kubebuilder:validation:Optional
	RouteTo *string `json:"routeTo,omitempty" tf:"route_to,omitempty"`

	// sets Severity of the resulting alert. Allowed values are: info, error, warning, critical
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// Set whether the resulting alert is suppressed. Suppressed alerts will not trigger an incident.
	// +kubebuilder:validation:Optional
	Suppress *bool `json:"suppress,omitempty" tf:"suppress,omitempty"`

	// The number of seconds to suspend the resulting alert before triggering. This effectively pauses incident notifications. If a resolve event arrives before the alert triggers then PagerDuty won't create an incident for this alert.
	// +kubebuilder:validation:Optional
	Suspend *float64 `json:"suspend,omitempty" tf:"suspend,omitempty"`

	// Populate variables from event payloads and use those variables in other event actions.
	// +kubebuilder:validation:Optional
	Variable []RuleActionsVariableParameters `json:"variable,omitempty" tf:"variable,omitempty"`
}

type OrchestrationServiceSetRuleInitParameters struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	Actions []OrchestrationServiceSetRuleActionsInitParameters `json:"actions,omitempty" tf:"actions,omitempty"`

	// Each of these conditions is evaluated to check if an event matches this rule. The rule is considered a match if any of these conditions match. If none are provided, the event will always match against the rule.
	Condition []SetRuleConditionInitParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// Indicates whether the rule is disabled and would therefore not be evaluated.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// A description of this rule's purpose.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`
}

type OrchestrationServiceSetRuleObservation struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	Actions []OrchestrationServiceSetRuleActionsObservation `json:"actions,omitempty" tf:"actions,omitempty"`

	// Each of these conditions is evaluated to check if an event matches this rule. The rule is considered a match if any of these conditions match. If none are provided, the event will always match against the rule.
	Condition []SetRuleConditionObservation `json:"condition,omitempty" tf:"condition,omitempty"`

	// Indicates whether the rule is disabled and would therefore not be evaluated.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A description of this rule's purpose.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`
}

type OrchestrationServiceSetRuleParameters struct {

	// Actions that will be taken to change the resulting alert and incident, when an event matches this rule.
	// +kubebuilder:validation:Optional
	Actions []OrchestrationServiceSetRuleActionsParameters `json:"actions" tf:"actions,omitempty"`

	// Each of these conditions is evaluated to check if an event matches this rule. The rule is considered a match if any of these conditions match. If none are provided, the event will always match against the rule.
	// +kubebuilder:validation:Optional
	Condition []SetRuleConditionParameters `json:"condition,omitempty" tf:"condition,omitempty"`

	// Indicates whether the rule is disabled and would therefore not be evaluated.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// A description of this rule's purpose.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`
}

type PagerdutyAutomationActionInitParameters struct {

	// Id of the Process Automation action to be triggered.
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`
}

type PagerdutyAutomationActionObservation struct {

	// Id of the Process Automation action to be triggered.
	ActionID *string `json:"actionId,omitempty" tf:"action_id,omitempty"`
}

type PagerdutyAutomationActionParameters struct {

	// Id of the Process Automation action to be triggered.
	// +kubebuilder:validation:Optional
	ActionID *string `json:"actionId" tf:"action_id,omitempty"`
}

type RuleActionsAutomationActionHeaderInitParameters struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsAutomationActionHeaderObservation struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsAutomationActionHeaderParameters struct {

	// Name to identify the header
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type RuleActionsAutomationActionInitParameters struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	Header []RuleActionsAutomationActionHeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	Parameter []RuleActionsAutomationActionParameterInitParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RuleActionsAutomationActionObservation struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	Header []RuleActionsAutomationActionHeaderObservation `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	Parameter []RuleActionsAutomationActionParameterObservation `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type RuleActionsAutomationActionParameterInitParameters struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsAutomationActionParameterObservation struct {

	// Name to identify the header
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsAutomationActionParameterParameters struct {

	// Name to identify the header
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type RuleActionsAutomationActionParameters struct {

	// When true, PagerDuty's servers will automatically send this webhook request as soon as the resulting incident is created. When false, your incident responder will be able to manually trigger the Webhook via the PagerDuty website and mobile app.
	// +kubebuilder:validation:Optional
	AutoSend *bool `json:"autoSend,omitempty" tf:"auto_send,omitempty"`

	// Specify custom key/value pairs that'll be sent with the webhook request as request headers.
	// +kubebuilder:validation:Optional
	Header []RuleActionsAutomationActionHeaderParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Name of this Webhook.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Specify custom key/value pairs that'll be included in the webhook request's JSON payload.
	// +kubebuilder:validation:Optional
	Parameter []RuleActionsAutomationActionParameterParameters `json:"parameter,omitempty" tf:"parameter,omitempty"`

	// The API endpoint where PagerDuty's servers will send the webhook request.
	// +kubebuilder:validation:Optional
	URL *string `json:"url" tf:"url,omitempty"`
}

type RuleActionsExtractionInitParameters struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type RuleActionsExtractionObservation struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	Target *string `json:"target,omitempty" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type RuleActionsExtractionParameters struct {

	// A RE2 regular expression that will be matched against field specified via the source argument. If the regex contains one or more capture groups, their values will be extracted and appended together. If it contains no capture groups, the whole match is used. This field can be ignored for template based extractions.
	// +kubebuilder:validation:Optional
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// The path to the event field where the regex will be applied to extract a value. You can use any valid PCL path like event.summary and you can reference previously-defined variables using a path like variables.hostname. This field can be ignored for template based extractions.
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// The PagerDuty Common Event Format PD-CEF field that will be set with the value from the template or based on regex and source fields.
	// +kubebuilder:validation:Optional
	Target *string `json:"target" tf:"target,omitempty"`

	// A string that will be used to populate the target field. You can reference variables or event data within your template using double curly braces. For example:
	// +kubebuilder:validation:Optional
	Template *string `json:"template,omitempty" tf:"template,omitempty"`
}

type RuleActionsIncidentCustomFieldUpdateInitParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsIncidentCustomFieldUpdateObservation struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsIncidentCustomFieldUpdateParameters struct {

	// The ID of this set of rules. Rules in other sets can route events into this set using the rule's route_to property.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type RuleActionsVariableInitParameters struct {

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Only regex is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsVariableObservation struct {

	// Name of this Webhook.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// Only regex is supported
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The value to assign to this custom field
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RuleActionsVariableParameters struct {

	// Name of this Webhook.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Path to a field in an event, in dot-notation. This supports both PagerDuty Common Event Format PD-CEF and non-CEF fields. Eg: Use event.summary for the summary CEF field. Use raw_event.fieldname to read from the original event fieldname data. You can use any valid PCL path.
	// +kubebuilder:validation:Optional
	Path *string `json:"path" tf:"path,omitempty"`

	// Only regex is supported
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`

	// The value to assign to this custom field
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type SetRuleConditionInitParameters struct {

	// A PCL condition string.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`
}

type SetRuleConditionObservation struct {

	// A PCL condition string.
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`
}

type SetRuleConditionParameters struct {

	// A PCL condition string.
	// +kubebuilder:validation:Optional
	Expression *string `json:"expression" tf:"expression,omitempty"`
}

// OrchestrationServiceSpec defines the desired state of OrchestrationService
type OrchestrationServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrchestrationServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrchestrationServiceInitParameters `json:"initProvider,omitempty"`
}

// OrchestrationServiceStatus defines the observed state of OrchestrationService.
type OrchestrationServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrchestrationServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrchestrationService is the Schema for the OrchestrationServices API. Creates and manages a Service Orchestration for a Service.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,pagerduty}
type OrchestrationService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.catchAll) || (has(self.initProvider) && has(self.initProvider.catchAll))",message="spec.forProvider.catchAll is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.set) || (has(self.initProvider) && has(self.initProvider.set))",message="spec.forProvider.set is a required parameter"
	Spec   OrchestrationServiceSpec   `json:"spec"`
	Status OrchestrationServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrchestrationServiceList contains a list of OrchestrationServices
type OrchestrationServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrchestrationService `json:"items"`
}

// Repository type metadata.
var (
	OrchestrationService_Kind             = "OrchestrationService"
	OrchestrationService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrchestrationService_Kind}.String()
	OrchestrationService_KindAPIVersion   = OrchestrationService_Kind + "." + CRDGroupVersion.String()
	OrchestrationService_GroupVersionKind = CRDGroupVersion.WithKind(OrchestrationService_Kind)
)

func init() {
	SchemeBuilder.Register(&OrchestrationService{}, &OrchestrationServiceList{})
}
