/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-pagerduty/apis/team/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Policy.
func (mg *Policy) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Teams),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.TeamRefs,
		Selector:      mg.Spec.ForProvider.TeamSelector,
		To: reference.To{
			List:    &v1alpha1.TeamList{},
			Managed: &v1alpha1.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Teams")
	}
	mg.Spec.ForProvider.Teams = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.TeamRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Teams),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.TeamRefs,
		Selector:      mg.Spec.InitProvider.TeamSelector,
		To: reference.To{
			List:    &v1alpha1.TeamList{},
			Managed: &v1alpha1.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Teams")
	}
	mg.Spec.InitProvider.Teams = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.TeamRefs = mrsp.ResolvedReferences

	return nil
}
