/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyInitParameters struct {

	// A human-friendly description of the escalation policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the escalation policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of times the escalation policy will repeat after reaching the end of its escalation.
	NumLoops *float64 `json:"numLoops,omitempty" tf:"num_loops,omitempty"`

	// An Escalation rule block. Escalation rules documented below.
	Rule []RuleInitParameters `json:"rule,omitempty" tf:"rule,omitempty"`
}

type PolicyObservation struct {

	// A human-friendly description of the escalation policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A target ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the escalation policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of times the escalation policy will repeat after reaching the end of its escalation.
	NumLoops *float64 `json:"numLoops,omitempty" tf:"num_loops,omitempty"`

	// An Escalation rule block. Escalation rules documented below.
	Rule []RuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// Team associated with the policy (Only 1 team can be assigned to an Escalation Policy). Account must have the teams ability to use this parameter.
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type PolicyParameters struct {

	// A human-friendly description of the escalation policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the escalation policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The number of times the escalation policy will repeat after reaching the end of its escalation.
	// +kubebuilder:validation:Optional
	NumLoops *float64 `json:"numLoops,omitempty" tf:"num_loops,omitempty"`

	// An Escalation rule block. Escalation rules documented below.
	// +kubebuilder:validation:Optional
	Rule []RuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// References to Team in team to populate teams.
	// +kubebuilder:validation:Optional
	TeamRefs []v1.Reference `json:"teamRefs,omitempty" tf:"-"`

	// Selector for a list of Team in team to populate teams.
	// +kubebuilder:validation:Optional
	TeamSelector *v1.Selector `json:"teamSelector,omitempty" tf:"-"`

	// Team associated with the policy (Only 1 team can be assigned to an Escalation Policy). Account must have the teams ability to use this parameter.
	// +crossplane:generate:reference:type=github.com/crossplane-contrib/provider-pagerduty/apis/team/v1alpha1.Team
	// +crossplane:generate:reference:refFieldName=TeamRefs
	// +crossplane:generate:reference:selectorFieldName=TeamSelector
	// +kubebuilder:validation:Optional
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`
}

type RuleInitParameters struct {

	// The number of minutes before an unacknowledged incident escalates away from this rule.
	EscalationDelayInMinutes *float64 `json:"escalationDelayInMinutes,omitempty" tf:"escalation_delay_in_minutes,omitempty"`

	Target []TargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type RuleObservation struct {

	// The number of minutes before an unacknowledged incident escalates away from this rule.
	EscalationDelayInMinutes *float64 `json:"escalationDelayInMinutes,omitempty" tf:"escalation_delay_in_minutes,omitempty"`

	// A target ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Target []TargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type RuleParameters struct {

	// The number of minutes before an unacknowledged incident escalates away from this rule.
	// +kubebuilder:validation:Optional
	EscalationDelayInMinutes *float64 `json:"escalationDelayInMinutes,omitempty" tf:"escalation_delay_in_minutes,omitempty"`

	// +kubebuilder:validation:Optional
	Target []TargetParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type TargetInitParameters struct {

	// A target ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Can be user_reference or schedule_reference. Defaults to user_reference. For multiple users as example, repeat the target.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TargetObservation struct {

	// A target ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Can be user_reference or schedule_reference. Defaults to user_reference. For multiple users as example, repeat the target.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TargetParameters struct {

	// A target ID
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Can be user_reference or schedule_reference. Defaults to user_reference. For multiple users as example, repeat the target.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// PolicySpec defines the desired state of Policy
type PolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyInitParameters `json:"initProvider,omitempty"`
}

// PolicyStatus defines the observed state of Policy.
type PolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Policy is the Schema for the Policys API. Creates and manages an escalation policy in PagerDuty.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,pagerduty}
type Policy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.rule) || has(self.initProvider.rule)",message="rule is a required parameter"
	Spec   PolicySpec   `json:"spec"`
	Status PolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyList contains a list of Policys
type PolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Policy `json:"items"`
}

// Repository type metadata.
var (
	Policy_Kind             = "Policy"
	Policy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Policy_Kind}.String()
	Policy_KindAPIVersion   = Policy_Kind + "." + CRDGroupVersion.String()
	Policy_GroupVersionKind = CRDGroupVersion.WithKind(Policy_Kind)
)

func init() {
	SchemeBuilder.Register(&Policy{}, &PolicyList{})
}
