apiVersion: automation.pagerduty.m.crossplane.io/v1alpha1
kind: ActionsActionTeamAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/actionsactionteamassociation
  labels:
    testing.upbound.io/example-name: foo
  name: foo
  namespace: crossplane-system
spec:
  forProvider:
    actionId: ${pagerduty_automation_actions_action.pa_action_example.id}
    teamId: ${pagerduty_team.example.id}

---

apiVersion: automation.pagerduty.m.crossplane.io/v1alpha1
kind: ActionsAction
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/actionsactionteamassociation
  labels:
    testing.upbound.io/example-name: pa_action_example
  name: pa-action-example
  namespace: crossplane-system
spec:
  forProvider:
    actionDataReference:
    - processAutomationJobId: P123456
    actionType: process_automation
    description: Description of the PA Action created via TF
    name: PA Action created via TF

---

apiVersion: team.pagerduty.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/actionsactionteamassociation
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: All engineering
    name: Engineering
