apiVersion: automation.actions.pagerduty.m.crossplane.io/v1alpha1
kind: Runner
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/runner
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: Description of the Runner created via TF
    name: Runner created via TF
    runbookApiKeySecretRef:
      key: example-key
      name: example-secret
    runbookBaseUri: rdcat.stg
    runnerType: runbook
