apiVersion: automation.actions.pagerduty.m.crossplane.io/v1alpha1
kind: RunnerTeamAssociation
metadata:
  annotations:
    meta.upbound.io/example-id: automation/v1alpha1/runnerteamassociation
  labels:
    testing.upbound.io/example-name: pa_runner_ent_eng_assoc
  name: pa-runner-ent-eng-assoc
  namespace: upbound-system
spec:
  forProvider:
    runnerSelector:
      matchLabels:
        testing.upbound.io/example-name: pa_runbook_runner
    teamIdSelector:
      matchLabels:
        testing.upbound.io/example-name: team_ent_eng

---

apiVersion: automation.actions.pagerduty.m.crossplane.io/v1alpha1
kind: Runner
metadata:
  annotations:
    meta.upbound.io/example-id: automation.actions/v1alpha1/runnerteamassociation
  labels:
    testing.upbound.io/example-name: pa_runbook_runner
  name: pa-runbook-runner
  namespace: upbound-system
spec:
  forProvider:
    description: Description of the Runner created via TF
    name: Runner created via TF
    runbookApiKeySecretRef:
      key: example-key
      name: example-secret
    runbookBaseUri: cat-cat
    runnerType: runbook

---

apiVersion: team.pagerduty.m.crossplane.io/v1alpha1
kind: Team
metadata:
  annotations:
    meta.upbound.io/example-id: automation.actions/v1alpha1/runnerteamassociation
  labels:
    testing.upbound.io/example-name: team_ent_eng
  name: team-ent-eng
  namespace: upbound-system
spec:
  forProvider:
    description: Enterprise engineering
    name: Enterprise Engineering
