/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *Action) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Runner) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *RunnerTeamAssociation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ServiceAssociation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamAssociation) Hub() {}
