/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ActionDataReferenceInitParameters struct {

	// The command to execute the script with.
	InvocationCommand *string `json:"invocationCommand,omitempty" tf:"invocation_command,omitempty"`

	// The arguments to pass to the Process Automation job execution.
	ProcessAutomationJobArguments *string `json:"processAutomationJobArguments,omitempty" tf:"process_automation_job_arguments,omitempty"`

	// The ID of the Process Automation job to execute.
	ProcessAutomationJobID *string `json:"processAutomationJobId,omitempty" tf:"process_automation_job_id,omitempty"`

	// The expression that filters on which nodes a Process Automation Job executes Learn more.
	ProcessAutomationNodeFilter *string `json:"processAutomationNodeFilter,omitempty" tf:"process_automation_node_filter,omitempty"`

	// Body of the script to be executed on the Runner. Max length is 16777215 characters.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type ActionDataReferenceObservation struct {

	// The command to execute the script with.
	InvocationCommand *string `json:"invocationCommand,omitempty" tf:"invocation_command,omitempty"`

	// The arguments to pass to the Process Automation job execution.
	ProcessAutomationJobArguments *string `json:"processAutomationJobArguments,omitempty" tf:"process_automation_job_arguments,omitempty"`

	// The ID of the Process Automation job to execute.
	ProcessAutomationJobID *string `json:"processAutomationJobId,omitempty" tf:"process_automation_job_id,omitempty"`

	// The expression that filters on which nodes a Process Automation Job executes Learn more.
	ProcessAutomationNodeFilter *string `json:"processAutomationNodeFilter,omitempty" tf:"process_automation_node_filter,omitempty"`

	// Body of the script to be executed on the Runner. Max length is 16777215 characters.
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type ActionDataReferenceParameters struct {

	// The command to execute the script with.
	// +kubebuilder:validation:Optional
	InvocationCommand *string `json:"invocationCommand,omitempty" tf:"invocation_command,omitempty"`

	// The arguments to pass to the Process Automation job execution.
	// +kubebuilder:validation:Optional
	ProcessAutomationJobArguments *string `json:"processAutomationJobArguments,omitempty" tf:"process_automation_job_arguments,omitempty"`

	// The ID of the Process Automation job to execute.
	// +kubebuilder:validation:Optional
	ProcessAutomationJobID *string `json:"processAutomationJobId,omitempty" tf:"process_automation_job_id,omitempty"`

	// The expression that filters on which nodes a Process Automation Job executes Learn more.
	// +kubebuilder:validation:Optional
	ProcessAutomationNodeFilter *string `json:"processAutomationNodeFilter,omitempty" tf:"process_automation_node_filter,omitempty"`

	// Body of the script to be executed on the Runner. Max length is 16777215 characters.
	// +kubebuilder:validation:Optional
	Script *string `json:"script,omitempty" tf:"script,omitempty"`
}

type ActionInitParameters struct {

	// The category of the action. The only allowed values are diagnostic and remediation.
	ActionClassification *string `json:"actionClassification,omitempty" tf:"action_classification,omitempty"`

	// Action Data block. Action Data is documented below.
	ActionDataReference []ActionDataReferenceInitParameters `json:"actionDataReference,omitempty" tf:"action_data_reference,omitempty"`

	// The type of the action. The only allowed values are process_automation and script. Cannot be changed once set.
	ActionType *string `json:"actionType,omitempty" tf:"action_type,omitempty"`

	// Whether the action can be invoked automatically from a PagerDuty Event Orchestration.
	AllowInvocationFromEventOrchestration *string `json:"allowInvocationFromEventOrchestration,omitempty" tf:"allow_invocation_from_event_orchestration,omitempty"`

	// Whether the action can be invoked manually by a user on the PagerDuty website.
	AllowInvocationManually *string `json:"allowInvocationManually,omitempty" tf:"allow_invocation_manually,omitempty"`

	// The time action was created. Represented as an ISO 8601 timestamp.
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// The description of the action. Max length is 1024 characters.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// If true, the action will be associated with every service.
	MapToAllServices *bool `json:"mapToAllServices,omitempty" tf:"map_to_all_services,omitempty"`

	// The last time action has been modified. Represented as an ISO 8601 timestamp.
	ModifyTime *string `json:"modifyTime,omitempty" tf:"modify_time,omitempty"`

	// The name of the action. Max length is 255 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the action can be invoked on unresolved incidents.
	OnlyInvocableOnUnresolvedIncidents *bool `json:"onlyInvocableOnUnresolvedIncidents,omitempty" tf:"only_invocable_on_unresolved_incidents,omitempty"`

	// The Process Automation Actions runner to associate the action with. Cannot be changed for the process_automation action type once set.
	RunnerID *string `json:"runnerId,omitempty" tf:"runner_id,omitempty"`

	// The type of the runner associated with the action.
	RunnerType *string `json:"runnerType,omitempty" tf:"runner_type,omitempty"`

	// The type of object. The value returned will be action.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ActionObservation struct {

	// The category of the action. The only allowed values are diagnostic and remediation.
	ActionClassification *string `json:"actionClassification,omitempty" tf:"action_classification,omitempty"`

	// Action Data block. Action Data is documented below.
	ActionDataReference []ActionDataReferenceObservation `json:"actionDataReference,omitempty" tf:"action_data_reference,omitempty"`

	// The type of the action. The only allowed values are process_automation and script. Cannot be changed once set.
	ActionType *string `json:"actionType,omitempty" tf:"action_type,omitempty"`

	// Whether the action can be invoked automatically from a PagerDuty Event Orchestration.
	AllowInvocationFromEventOrchestration *string `json:"allowInvocationFromEventOrchestration,omitempty" tf:"allow_invocation_from_event_orchestration,omitempty"`

	// Whether the action can be invoked manually by a user on the PagerDuty website.
	AllowInvocationManually *string `json:"allowInvocationManually,omitempty" tf:"allow_invocation_manually,omitempty"`

	// The time action was created. Represented as an ISO 8601 timestamp.
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// The description of the action. Max length is 1024 characters.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the action.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If true, the action will be associated with every service.
	MapToAllServices *bool `json:"mapToAllServices,omitempty" tf:"map_to_all_services,omitempty"`

	// The last time action has been modified. Represented as an ISO 8601 timestamp.
	ModifyTime *string `json:"modifyTime,omitempty" tf:"modify_time,omitempty"`

	// The name of the action. Max length is 255 characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the action can be invoked on unresolved incidents.
	OnlyInvocableOnUnresolvedIncidents *bool `json:"onlyInvocableOnUnresolvedIncidents,omitempty" tf:"only_invocable_on_unresolved_incidents,omitempty"`

	// The Process Automation Actions runner to associate the action with. Cannot be changed for the process_automation action type once set.
	RunnerID *string `json:"runnerId,omitempty" tf:"runner_id,omitempty"`

	// The type of the runner associated with the action.
	RunnerType *string `json:"runnerType,omitempty" tf:"runner_type,omitempty"`

	// The type of object. The value returned will be action.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ActionParameters struct {

	// The category of the action. The only allowed values are diagnostic and remediation.
	// +kubebuilder:validation:Optional
	ActionClassification *string `json:"actionClassification,omitempty" tf:"action_classification,omitempty"`

	// Action Data block. Action Data is documented below.
	// +kubebuilder:validation:Optional
	ActionDataReference []ActionDataReferenceParameters `json:"actionDataReference,omitempty" tf:"action_data_reference,omitempty"`

	// The type of the action. The only allowed values are process_automation and script. Cannot be changed once set.
	// +kubebuilder:validation:Optional
	ActionType *string `json:"actionType,omitempty" tf:"action_type,omitempty"`

	// Whether the action can be invoked automatically from a PagerDuty Event Orchestration.
	// +kubebuilder:validation:Optional
	AllowInvocationFromEventOrchestration *string `json:"allowInvocationFromEventOrchestration,omitempty" tf:"allow_invocation_from_event_orchestration,omitempty"`

	// Whether the action can be invoked manually by a user on the PagerDuty website.
	// +kubebuilder:validation:Optional
	AllowInvocationManually *string `json:"allowInvocationManually,omitempty" tf:"allow_invocation_manually,omitempty"`

	// The time action was created. Represented as an ISO 8601 timestamp.
	// +kubebuilder:validation:Optional
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// The description of the action. Max length is 1024 characters.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// If true, the action will be associated with every service.
	// +kubebuilder:validation:Optional
	MapToAllServices *bool `json:"mapToAllServices,omitempty" tf:"map_to_all_services,omitempty"`

	// The last time action has been modified. Represented as an ISO 8601 timestamp.
	// +kubebuilder:validation:Optional
	ModifyTime *string `json:"modifyTime,omitempty" tf:"modify_time,omitempty"`

	// The name of the action. Max length is 255 characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Whether the action can be invoked on unresolved incidents.
	// +kubebuilder:validation:Optional
	OnlyInvocableOnUnresolvedIncidents *bool `json:"onlyInvocableOnUnresolvedIncidents,omitempty" tf:"only_invocable_on_unresolved_incidents,omitempty"`

	// The Process Automation Actions runner to associate the action with. Cannot be changed for the process_automation action type once set.
	// +kubebuilder:validation:Optional
	RunnerID *string `json:"runnerId,omitempty" tf:"runner_id,omitempty"`

	// The type of the runner associated with the action.
	// +kubebuilder:validation:Optional
	RunnerType *string `json:"runnerType,omitempty" tf:"runner_type,omitempty"`

	// The type of object. The value returned will be action.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ActionSpec defines the desired state of Action
type ActionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ActionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ActionInitParameters `json:"initProvider,omitempty"`
}

// ActionStatus defines the observed state of Action.
type ActionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ActionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Action is the Schema for the Actions API. Creates and manages an Automation Actions action in PagerDuty.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,pagerduty}
type Action struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.actionDataReference) || (has(self.initProvider) && has(self.initProvider.actionDataReference))",message="spec.forProvider.actionDataReference is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.actionType) || (has(self.initProvider) && has(self.initProvider.actionType))",message="spec.forProvider.actionType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ActionSpec   `json:"spec"`
	Status ActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ActionList contains a list of Actions
type ActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Action `json:"items"`
}

// Repository type metadata.
var (
	Action_Kind             = "Action"
	Action_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Action_Kind}.String()
	Action_KindAPIVersion   = Action_Kind + "." + CRDGroupVersion.String()
	Action_GroupVersionKind = CRDGroupVersion.WithKind(Action_Kind)
)

func init() {
	SchemeBuilder.Register(&Action{}, &ActionList{})
}
