/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-pagerduty/apis/namespaced/service/v1alpha1"
	v1alpha11 "github.com/crossplane-contrib/provider-pagerduty/apis/namespaced/team/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ActionServiceAssociation.
func (mg *ActionServiceAssociation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ActionID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ActionIDRef,
		Selector:     mg.Spec.ForProvider.ActionIDSelector,
		To: reference.To{
			List:    &ActionList{},
			Managed: &Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ActionID")
	}
	mg.Spec.ForProvider.ActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ActionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ServiceID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ServiceIDRef,
		Selector:     mg.Spec.ForProvider.ServiceIDSelector,
		To: reference.To{
			List:    &v1alpha1.ServiceList{},
			Managed: &v1alpha1.Service{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ServiceID")
	}
	mg.Spec.ForProvider.ServiceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ServiceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ActionID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ActionIDRef,
		Selector:     mg.Spec.InitProvider.ActionIDSelector,
		To: reference.To{
			List:    &ActionList{},
			Managed: &Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ActionID")
	}
	mg.Spec.InitProvider.ActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ActionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ServiceID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ServiceIDRef,
		Selector:     mg.Spec.InitProvider.ServiceIDSelector,
		To: reference.To{
			List:    &v1alpha1.ServiceList{},
			Managed: &v1alpha1.Service{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ServiceID")
	}
	mg.Spec.InitProvider.ServiceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ServiceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ActionTeamAssociation.
func (mg *ActionTeamAssociation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ActionID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ActionIDRef,
		Selector:     mg.Spec.ForProvider.ActionIDSelector,
		To: reference.To{
			List:    &ActionList{},
			Managed: &Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ActionID")
	}
	mg.Spec.ForProvider.ActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ActionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TeamID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TeamIDRef,
		Selector:     mg.Spec.ForProvider.TeamIDSelector,
		To: reference.To{
			List:    &v1alpha11.TeamList{},
			Managed: &v1alpha11.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TeamID")
	}
	mg.Spec.ForProvider.TeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TeamIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ActionID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ActionIDRef,
		Selector:     mg.Spec.InitProvider.ActionIDSelector,
		To: reference.To{
			List:    &ActionList{},
			Managed: &Action{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ActionID")
	}
	mg.Spec.InitProvider.ActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ActionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TeamID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TeamIDRef,
		Selector:     mg.Spec.InitProvider.TeamIDSelector,
		To: reference.To{
			List:    &v1alpha11.TeamList{},
			Managed: &v1alpha11.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TeamID")
	}
	mg.Spec.InitProvider.TeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TeamIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this RunnerTeamAssociation.
func (mg *RunnerTeamAssociation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TeamID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TeamIDRef,
		Selector:     mg.Spec.ForProvider.TeamIDSelector,
		To: reference.To{
			List:    &v1alpha11.TeamList{},
			Managed: &v1alpha11.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TeamID")
	}
	mg.Spec.ForProvider.TeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TeamIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TeamID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TeamIDRef,
		Selector:     mg.Spec.InitProvider.TeamIDSelector,
		To: reference.To{
			List:    &v1alpha11.TeamList{},
			Managed: &v1alpha11.Team{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TeamID")
	}
	mg.Spec.InitProvider.TeamID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TeamIDRef = rsp.ResolvedReference

	return nil
}
