/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CustomFieldInitParameters struct {

	// The data type of the field. Must be one of string, integer, float, boolean, datetime, or url.
	DataType *string `json:"dataType,omitempty" tf:"data_type,omitempty"`

	// The default value to set when new incidents are created. Always specified as a string.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of the field.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the field.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The field type of the field. Must be one of single_value, single_value_fixed, multi_value, or multi_value_fixed.
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	// The name of the field.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CustomFieldObservation struct {

	// The data type of the field. Must be one of string, integer, float, boolean, datetime, or url.
	DataType *string `json:"dataType,omitempty" tf:"data_type,omitempty"`

	// The default value to set when new incidents are created. Always specified as a string.
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of the field.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the field.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The field type of the field. Must be one of single_value, single_value_fixed, multi_value, or multi_value_fixed.
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	// The ID of the field.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the field.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CustomFieldParameters struct {

	// The data type of the field. Must be one of string, integer, float, boolean, datetime, or url.
	// +kubebuilder:validation:Optional
	DataType *string `json:"dataType,omitempty" tf:"data_type,omitempty"`

	// The default value to set when new incidents are created. Always specified as a string.
	// +kubebuilder:validation:Optional
	DefaultValue *string `json:"defaultValue,omitempty" tf:"default_value,omitempty"`

	// The description of the field.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of the field.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The field type of the field. Must be one of single_value, single_value_fixed, multi_value, or multi_value_fixed.
	// +kubebuilder:validation:Optional
	FieldType *string `json:"fieldType,omitempty" tf:"field_type,omitempty"`

	// The name of the field.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// CustomFieldSpec defines the desired state of CustomField
type CustomFieldSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomFieldParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomFieldInitParameters `json:"initProvider,omitempty"`
}

// CustomFieldStatus defines the observed state of CustomField.
type CustomFieldStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomFieldObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomField is the Schema for the CustomFields API. Creates and manages an Incident Custom Field in PagerDuty.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,pagerduty}
type CustomField struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataType) || (has(self.initProvider) && has(self.initProvider.dataType))",message="spec.forProvider.dataType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fieldType) || (has(self.initProvider) && has(self.initProvider.fieldType))",message="spec.forProvider.fieldType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CustomFieldSpec   `json:"spec"`
	Status CustomFieldStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomFieldList contains a list of CustomFields
type CustomFieldList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomField `json:"items"`
}

// Repository type metadata.
var (
	CustomField_Kind             = "CustomField"
	CustomField_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomField_Kind}.String()
	CustomField_KindAPIVersion   = CustomField_Kind + "." + CRDGroupVersion.String()
	CustomField_GroupVersionKind = CRDGroupVersion.WithKind(CustomField_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomField{}, &CustomFieldList{})
}
