/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/crossplane-contrib/provider-pagerduty/apis/team/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Rule.
func (mg *Rule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ruleset),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.RulesetRef,
		Selector:     mg.Spec.ForProvider.RulesetSelector,
		To: reference.To{
			List:    &RulesetList{},
			Managed: &Ruleset{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Ruleset")
	}
	mg.Spec.ForProvider.Ruleset = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RulesetRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Ruleset.
func (mg *Ruleset) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Team); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Team[i3].ID),
			Extract:      reference.ExternalName(),
			Reference:    mg.Spec.ForProvider.Team[i3].IDRef,
			Selector:     mg.Spec.ForProvider.Team[i3].IDSelector,
			To: reference.To{
				List:    &v1alpha1.TeamList{},
				Managed: &v1alpha1.Team{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Team[i3].ID")
		}
		mg.Spec.ForProvider.Team[i3].ID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Team[i3].IDRef = rsp.ResolvedReference

	}

	return nil
}
